FROM python:3.10-slim

WORKDIR /app

COPY requirements.trainer.txt .
RUN pip install --no-cache-dir -r requirements.trainer.txt

COPY training/train_with_mlflow.py .

# Ждём 15 секунд чтобы MLflow успел полностью подняться
CMD ["sh", "-c", "sleep 15 && python train_with_mlflow.py"]